events/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'event'

urlpatterns = [
    path('', views.index, name="index"),
    path('event_detail/<id>/', views.event_detail, name='event_detail'),
]

news/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'new'

urlpatterns = [
    path('', views.index, name="index"),
    path('news/', views.news, name="news"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('news_detail/<id>/', views.news_detail, name='news_detail'),
]

news_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('events/', include('events.urls')),
    path('gallery/', include('gallary.urls')),
    path('tinymce/', include('tinymce.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from tinymce.models import HTMLField

class Tags(models.Model):
	name = models.CharField(max_length=300)

	class Meta:
		verbose_name = 'tag'
		verbose_name_plural = 'tags'

	def __str__(self):
		return self.name

class Event(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=500)
	image = models.ImageField(default=False)
	little_discription = models.TextField(default=False)
	discription = HTMLField()
	futured = models.BooleanField(default=False)
	popular = models.BooleanField(default=False)
	likes=models.ManyToManyField(User, related_name="like", blank=True)
	# dislikes=models.ManyToManyField(User, related_name="q_disliked", blank=True)
	tags = models.ManyToManyField(Tags)
	event_start_date = models.DateTimeField(blank=True, null=True)
	event_end_date = models.DateTimeField(blank=True, null=True)
	date_updated = models.DateTimeField(auto_now=True)
	date_created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('event:event_detail', args=[self.id])

	def num_likes(self):
		return self.likes.count()

	# def num_dislikes(self):
	# 	return self.dislikes.count()

class EventComment(models.Model):
    question=models.ForeignKey(Event, related_name="comments", on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    comment=models.TextField()
    date_updated = models.DateTimeField(auto_now=True)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} comment"


class Email(models.Model):
	emais = models.EmailField()


	def __str__(self):
		return self.emais

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Tags(models.Model):
	name = models.CharField(max_length=300)

	class Meta:
		verbose_name = 'tag'
		verbose_name_plural = 'tags'

	def __str__(self):
		return self.name

class New(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=500)
	image = models.ImageField(default=False)
	little_discription = models.TextField(default=False)
	discription = models.TextField()
	futured = models.BooleanField(default=False)
	one = models.BooleanField(default=False)
	popular = models.BooleanField(default=False)
	approved = models.BooleanField(default=False)
	likes=models.ManyToManyField(User, related_name="love", blank=True)
	# dislikes=models.ManyToManyField(User, related_name="q_disliked", blank=True)
	tags = models.ManyToManyField(Tags)
	date_updated = models.DateTimeField(auto_now=True)
	date_created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('news_detail', kwargs={
			'id': self.id
		})
	def get_absolute_url(self):
		return reverse('new:forum_details', args=[self.id])

	def num_likes(self):
		return self.likes.count()

	# def num_dislikes(self):
	# 	return self.dislikes.count()

class NewsComment(models.Model):
	question=models.ForeignKey(New, related_name="comments", on_delete=models.CASCADE)
	user=models.ForeignKey(User, on_delete=models.CASCADE)
	comment=models.TextField()
	date_updated = models.DateTimeField(auto_now=True)
	created_at=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"{self.user.username} comment"


class Email(models.Model):
	emais = models.EmailField()


	def __str__(self):
		return self.emais

events/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
import json
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .models import *
# from users.models import *
from django.db.models import Sum



def index(request):
    event = Event.objects.all().order_by('-date_updated')[0:1]
    events = Event.objects.all()
    popular = Event.objects.filter(popular=True).order_by('-date_updated')[0:3]
    if request.method == 'POST':
        email = request.POST.get('EMAIL')
        Email.objects.create(emais=email)
    constant = {
        'event':event,
        'events':events,
        'popular':popular
    }
    return render(request,"events.html",{'event':event})




def event_detail(request, id):
    event = get_object_or_404(Event, id=id)
    popular = Event.objects.filter(popular=True).order_by('-date_updated')[0:3]
    event1 = Event.objects.all()[0:1]
    event2 = Event.objects.all()[2:4]
    if request.method == 'POST':
        email = request.POST.get('EMAIL')
        print("this the email",email)
        Email.objects.create(emais=email)
    context = {
        "event1":event1,
        "event2":event2,
        "event":event,
        'popular':popular,
    }
    return render(request, 'event_details.html',context)

news/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
import json
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .models import *
from gallary.models import *
from events.models import *
# from users.models import *
from django.db.models import Sum



def index(request):
    if request.method == 'POST':
        email = request.POST.get('EMAIL')
        print("this the email",email)
        Email.objects.create(emais=email)
    banners = New.objects.filter(futured=True).order_by('-date_updated')[0:2]
    lates = New.objects.filter(approved=True).order_by('-date_updated')[0:1]
    lates2 = New.objects.filter(approved=True).order_by('-date_updated')[1:2]
    news = New.objects.filter(approved=True)[0:1]
    news2 = New.objects.filter(approved=True)[2:3]
    banner = New.objects.filter(one=True).order_by('-date_updated')[0:1]

    gallery = Gallery.objects.all().order_by('-date_updated')[0:1]
    gallery2 = Gallery.objects.all()[0:2]
    gallery3 = Gallery.objects.all()[2:3]
    event2 = Event.objects.all()[0:2]
    event3 = Event.objects.all()[2:3]
    event4 = Event.objects.all()[3:5]
    # news = New.objects.all().order_by('-date_updated')[0:8]
    
    constant = {
        'lates':lates,
        'lates2':lates2,
        'banners':banners,
        'banner':banner,
        'news':news,
        'gallery2':gallery2,
        'gallery3':gallery3,
        'gallery':gallery,
        'event3':event3,
        'event4':event4,
        'event2':event2,
        'news2':news2
    }
    return render(request,"index.html",constant)


def about(request):
    if request.method == 'POST':
        email = request.POST.get('EMAIL')
        Email.objects.create(emais=email)
    pass
    return render(request,"kwabify/UserDashboard/finance-banks.html")


def contact(request):
    if request.method == 'POST':
        email = request.POST.get('EMAIL')
        Email.objects.create(emais=email)
    return render(request,"contact.html")


def news(request):
    news = New.objects.all().order_by('-date_updated')
    popular = New.objects.filter(popular=True).order_by('-date_updated')[0:3]
    if request.method == 'POST':
        email = request.POST.get('EMAIL')
        print("this the email",email)
        Email.objects.create(emais=email)
    constant = {
        'news':news,
        'popular':popular
    }
    return render(request,"news.html",constant)




def news_detail(request, id):
    news = get_object_or_404(New, id=id)
    popular = New.objects.filter(popular=True).order_by('-date_updated')[0:3]
    news1 = New.objects.filter(approved=True)[0:1]
    news2 = New.objects.filter(approved=True)[2:4]
    if request.method == 'POST':
        email = request.POST.get('EMAIL')
        print("this the email",email)
        Email.objects.create(emais=email)
    context = {
        "news1":news1,
        "news2":news2,
        "news":news,
        'popular':popular,
    }
    return render(request, 'news_details.html',context)

templates/contact.html
{% extends "base.html" %}


{% block content %}

            <div id="page_caption" class="  ">
                <div class="page_title_wrapper">
                    <div class="page_title_inner">
                        <div class="post_info_cat">
                            <div class="breadcrumb"><a href="index.html">Home</a> » Contact</div>
                        </div>
                        <h1><span>Contact</span></h1>
                    </div>
                </div>
            </div>

                <!-- Begin content -->
                <div id="page_content_wrapper" class="">
                    <div class="inner">
                        <!-- Begin main content -->
                        <div class="inner_wrapper">
                            <div class="sidebar_content full_width nopadding">
                                <div class="sidebar_content page_content">
                                    <p>
                                        Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
                                        Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.
                                    </p>
                                    <p>&nbsp;</p>
                                    <div class="one_third" style="">
                                        <h5>New York</h5>
                                        <p></p>
                                        <p>
                                            78 Collective Street, Manhattan<br />
                                            Kingston, United State
                                        </p>
                                        <p>
                                            +78 (0) 231 908 1433<br />
                                            +78 (0) 231 908 1456<br />
                                            <a href="#">mail@grandnewstheme.com</a>
                                        </p>
                                    </div>
                                    <div class="one_third" style="">
                                        <h5>London</h5>
                                        <p></p>
                                        <p>
                                            67 Collective Street, Yorksheer<br />
                                            Kingston, United Kingdom
                                        </p>
                                        <p>
                                            +78 (0) 231 908 1433<br />
                                            +78 (0) 231 908 1456<br />
                                            <a href="#">mail@grandnewstheme.com</a>
                                        </p>
                                    </div>
                                    <div class="one_third last" style="">
                                        <h5>Birmingham</h5>
                                        <p></p>
                                        <p>
                                            89 Collective Street, Manhattan<br />
                                            Kingston, United Kingdom
                                        </p>
                                        <p>
                                            +78 (0) 231 908 1433<br />
                                            +78 (0) 231 908 1456<br />
                                            <a href="#">mail@grandnewstheme.com</a>
                                        </p>
                                    </div>
                                    <p><br class="clear" /></p>
                                    <p></p>

                                    <div id="reponse_msg"><ul></ul></div>

                                    <form method="post" action="https://max-themes.net/demos/gnews/demo1/contactform/contactengine.php">
                                        
                                        <input type="text" name="Name" id="Name"  placeholder="Name:" class="input"/>
                                        
                                        <input type="text" name="City" id="City"  placeholder="City:" class="input"/>

                                        <input type="text" name="Email" id="Email"  placeholder="Email:" class="input"/>
                                        
                                        <textarea name="Message" rows="20" cols="20" id="Message" placeholder="Message:" class="input"></textarea>

                                        <input type="submit" name="submit" value="Submit" class="submit-button" />
                                    </form>
                                </div>

                                <div class="sidebar_wrapper">
                                    <div class="sidebar">
                                        <div class="content">
                                            <ul class="sidebar_widget">
                                                <li id="grand_news_social_profiles_posts-2" class="widget Grand_News_Social_Profiles_Posts">
                                                    <h2 class="widgettitle"><span>Socials</span></h2>
                                                    <div class="textwidget">
                                                        <div class="social_wrapper shortcode light small">
                                                            <ul>
                                                                <li class="facebook">
                                                                    <a target="_blank" title="Facebook" href="#"><i class="fa fa-facebook"></i></a>
                                                                </li>
                                                                <li class="twitter">
                                                                    <a target="_blank" title="Twitter" href="#"><i class="fa fa-twitter"></i></a>
                                                                </li>
                                                                <li class="youtube">
                                                                    <a target="_blank" title="Youtube" href="#"><i class="fa fa-youtube"></i></a>
                                                                </li>
                                                                <li class="vimeo">
                                                                    <a target="_blank" title="Vimeo" href="#"><i class="fa fa-vimeo-square"></i></a>
                                                                </li>
                                                                <li class="google">
                                                                    <a target="_blank" title="Google+" href="#"><i class="fa fa-google-plus"></i></a>
                                                                </li>
                                                                <li class="pinterest">
                                                                    <a target="_blank" title="Pinterest" href="#"><i class="fa fa-pinterest"></i></a>
                                                                </li>
                                                                <li class="instagram">
                                                                    <a target="_blank" title="Instagram" href="#"><i class="fa fa-instagram"></i></a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </li>
                                                <li id="grand_news_instagram-2" class="widget Grand_News_Instagram">
                                                    Required plugin "Meks Easy Photo Feed Widget" is required. <a href="#">Please install the plugin here</a>. or read more detailed instruction about
                                                    <a href="#" target="_blank">How to setup the plugin here</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <br class="clear" />
                                </div>
                            </div>
                        </div>
                        <!-- End main content -->
                    </div>
                </div>
                <br class="clear" />
                <br />



  {% endblock content %}  

templates/news.html
{% extends "base.html" %}
{% load static %}

{% block content %}
            <div id="page_caption" class="  ">
                <div class="page_title_wrapper">
                    <div class="page_title_inner">
                        <div class="post_info_cat">
                            <div class="breadcrumb"><a href="index.html">Home</a> » News</div>
                        </div>
                        <h1><span>News</span></h1>
                    </div>
                </div>
            </div>


            <!-- Begin content -->
            <div id="page_content_wrapper" class="">
                <div class="inner">
                    <!-- Begin main content -->
                    <div class="inner_wrapper">
                        <div class="sidebar_content">
                            <!-- Begin each blog post -->
                            {% for news in news %}
                            <div id="post-3761" class="post-3761 post type-post status-publish format-standard has-post-thumbnail hentry category-food category-lifestyle category-style category-topnews tag-bridge tag-lifestyle tag-travel">
                                <div class="post_wrapper">
                                    <div class="post_content_wrapper">
                                        <div class="post_header mixed">
                                            <div class="post_header_title">
                                                <div class="post_info_cat">
                                                    <span>
                                                        <a href="#">Food</a>
                                                        &nbsp;/
                                                        <a href="singleblog.html">Life Style</a>
                                                        &nbsp;/
                                                        <a href="singleblog.html">Style</a>
                                                        &nbsp;/
                                                        <a href="singleblog.html">Top News</a>
                                                    </span>
                                                </div>
                                                <h5>
                                                    <a href="{% url 'new:news_detail' news.id %}" title="{{news.title}}">
                                                        {{news.title}}
                                                    </a>
                                                </h5>
                                                <div class="post_detail post_date">
                                                    <span class="post_info_author">
                                                        <a href="{% url 'new:news_detail' news.id %}">
                                                            <span class="gravatar">
                                                                <img
                                                                    alt=""
                                                                    src="{{news.image.url}}"
                                                                    class="avatar avatar-60 photo"
                                                                    height="60"
                                                                    width="60"
                                                                    loading="lazy"
                                                                />
                                                            </span>
                                                            {{user.first_name}} {{user.last_name}}
                                                        </a>
                                                    </span>
                                                    <span class="post_info_date">
                                                        <a href="">Posted On {{news.date_updated|date}}</a>
                                                    </span>
                                                </div>
                                            </div>

                                            <br class="clear" />

                                            <div class="post_img">
                                                <a href="{% url 'new:news_detail' news.id %}">
                                                    <img src="{{news.image.url}}" alt="" class="" style="width: 960px; height: 640px;" />
                                                </a>
                                            </div>

                                            <br class="clear" />

                                            <p>
                                               {{news.little_discription}} [&hellip;]
                                            </p>

                                            <br class="clear" />

                                            <div class="post_button_wrapper">
                                                <a class="readmore" href="{% url 'new:news_detail' news.id %}">Continue Reading</a>
                                            </div>

                                            <div class="post_info_comment">
                                                <a href="singleblog.html"><i class="fa fa-commenting"></i>0</a>
                                            </div>

                                            <div class="post_info_view"><i class="fa fa-eye"></i>6.1K&nbsp;Views</div>

                                            <br class="clear" />
                                            <hr class="post_divider" />
                                            <hr class="post_divider double" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br class="clear" />
                            {% endfor %}
                            <!-- End each blog post -->

                            <!-- Begin each blog post -->
                           
                            <!-- End each blog post -->

                            <div class="pagination"><div class="pagination_page">1</div></div>
                        </div>

                        <div class="sidebar_wrapper">
                            <div class="sidebar">
                                <div class="content">
                                    <ul class="sidebar_widget">
                                        <li id="grand_news_custom_ads-4" class="widget Grand_News_Custom_Ads">
                                            <div class="ads_label">- Advertisement -</div>
                                            <img src="{% static 'upload/300x250ads.png' %}" alt="" />
                                        </li>
                                        <li id="mc4wp_form_widget-4" class="widget widget_mc4wp_form_widget">

                                            <h2 class="widgettitle"><span>Subscribe</span></h2>

                                            <form id="mc4wp-form-1" class="mc4wp-form mc4wp-form-618" method="post" data-id="618" data-name="Subscribe">
                                                {% csrf_token %}
                                                <div class="mc4wp-form-fields">
                                                    <div class="subscribe_tagline">
                                                        Get the recent popular stories straight into your inbox
                                                    </div>

                                                    <div class="subscribe_form">
                                                        <p>
                                                            <input type="email" name="EMAIL" placeholder="Email" required="" />
                                                        </p>

                                                        <p>
                                                            <input type="submit" value="Sign up" />
                                                        </p>
                                                    </div>
                                                </div>
                                                <label style="display: none !important;">Leave this field empty if you're human: <input type="text" name="_mc4wp_honeypot" value="" tabindex="-1" autocomplete="off" /></label>
                                                <input type="hidden" name="_mc4wp_timestamp" value="1654935617" /><input type="hidden" name="_mc4wp_form_id" value="618" /><input type="hidden" name="_mc4wp_form_element_id" value="mc4wp-form-1" />
                                                <div class="mc4wp-response"></div>
                                            </form>
                                            <!-- / Mailchimp for WordPress Plugin -->
                                        </li>
                                        <li id="grand_news_popular_posts-5" class="widget Grand_News_Popular_Posts">
                                            <h2 class="widgettitle"><span>Popular Posts</span></h2>
                                            <ul class="posts blog withthumb">
                                                
                                                {% for popular in popular %}
                                                <li>
                                                    <div class="post_circle_thumb">
                                                        <a href="singleblog.html">
                                                            <div class="post_number">1</div>
                                                            <img src="{{popular.image.url}}" class="tg-lazy" alt="" />
                                                        </a>
                                                    </div>
                                                    <a href="singleblog.html">{{popular.title}}</a>
                                                </li>
                                                {% endfor %}


                                                
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <br class="clear" />
                        </div>
                    </div>
                    <!-- End main content -->
                </div>
            </div>

  {% endblock content %}       